---
- name: Fedora configuration
  become: true
  become_user: root
  block:
    - name: (fedora) Install dependencies
      dnf:
        name:
          - httpd
          - python3-mod_wsgi
          - python3-jinja2
          - python3-markdown
          - python3-beautifulsoup4
          - libselinux-python
          - policycoreutils-python
          - python3-PyYAML
          - python3-jmespath
        state: latest

    - name: (fedora) Deploy apache configuration
      template:
        src: httpd.conf
        dest: /etc/httpd/conf.d/liftree.conf

    - name: (fedora) Manage firewalld
      firewalld:
        port: "{{ wsgi_port }}/tcp"
        permanent: yes
        state: enabled
        immediate: yes

    - name: (fedora) Reload apache config
      systemd:
        name: httpd
        state: reloaded
        enabled: yes
...