---
- debug: var=wsgi_user
- debug: var=git_clone
- debug: var=git_version
- debug: var=os_version
- debug: var=required.os

- name: Ensure pre-requiste
  assert:
    that:
      - os_version in required.os

- name: Deploy from git
  when: git_clone
  block:

    - name: Create user
      become: true
      become_user: root
      user:
        name: "{{ wsgi_user }}"
        comment: Liftree applicatif user
        shell: /bin/bash
  
    - name: Clone git repo on user home
      become: true
      become_user: "{{ wsgi_user }}"
      git:
        repo: "{{ git_repo }}"
        dest: /home/{{ wsgi_user }}/{{ git_name }}
        version: "{{ git_version }}"
        force: yes 

- name: Deploy liftree.conf for example
  template:
    src: example_liftree.conf
    dest: /home/{{ wsgi_user }}/liftree/apps/example/liftree.conf
    owner: "{{ wsgi_user }}"
    group: "{{ wsgi_user }}"

- name: Configure liftree
  become: true
  become_user: root
  block:

    - name: Create config directory
      file:
        path: /etc/liftree/conf.d/
        state: directory
        group: "{{ wsgi_user }}"

    - name: Deploy logging configuration
      template:
        src: logging.conf
        dest: /etc/liftree/logging.conf

    - name: Deploy liftree entry point configuration
      template:
        src: liftree.conf
        dest: /etc/liftree/liftree.conf

    - name: Deploy liftree example config
      copy:
        dest: /etc/liftree/conf.d/00-example.conf
        content: |
          ---
          name: /home/{{ wsgi_user }}/liftree/apps/example
          ...
    - name: Update permission to allow apache reach wsgi
      file:
        path: /home/{{ wsgi_user }}
        state: directory
        mode: 0755

- include_tasks: "{{ ansible_distribution|lower }}.yml"

- name: Test liftree installation
  block:

    - name: Final test
      uri:
        url: http://localhost/show
        return_content: true
      register: register_final_test
    
    # - debug: var=register_final_test
    
    - name: Check final test
      assert:
        that:
          - register_final_test.status == 200
          - register_final_test.content is search("<!-- unittest -->")
    
    - name: Display test url
      debug: msg="Go on http://{{ ansible_default_ipv4.address }}/show to test"
...