---
- name: selinux configuration
  become: true
  become_user: root
  tags:
    - selinux
  block:
    - name: Enable selinux boolean
      seboolean:
        name: "{{ item }}"
        state: yes
        persistent: yes
      loop:
        - httpd_enable_homedirs
        - httpd_read_user_content

    - name: Create empty files
      file:
        path: "{{ item }}"
        state: touch
        owner: "{{ wsgi_user }}"
        group: "{{ wsgi_user }}"
      loop:
        - "{{ liftree_generated_config }}"
        - "{{ liftree_logfile }}"

    - name: Set context for files
      sefcontext:
        target: "{{ item }}"
        setype: httpd_sys_rw_content_t
        state: present
      loop:
        - "{{ liftree_generated_config }}"
        - "{{ liftree_logfile }}"

    - name: Apply new SELinux file context
      command: restorecon -v {{ item }}
      loop:
        - "{{ liftree_generated_config }}"
        - "{{ liftree_logfile }}"

    - name: Remove genereted config
      file:
        path: "{{ liftree_generated_config }}"
        state: absent

    - name: Allow Apache to listen on tcp port {{ wsgi_port }}
      seport:
        ports: "{{ wsgi_port }}"
        proto: tcp
        setype: http_port_t
        state: present
...