---
- name: Ubuntu configuration
  become: true
  become_user: root
  block:
    - name: Install dependencies
      apt:
        name:
          - apache2
          - libapache2-mod-wsgi-py3
          - python3-jinja2
          - python3-markdown
          - python3-bs4
          - python3-jmespath
        state: latest

    - name: Deploy apache configuration
      template:
        src: httpd.conf
        dest: /etc/apache2/sites-available/wapi.conf

    - name: Use a2* command to enable {{ git_name }} site
      shell: "{{ item }}"
      loop:
        - "a2enmod http2"
        - "a2enmod headers"
        - "a2ensite {{ git_name }}.conf"

    - name: Reload apache config
      systemd:
        name: apache2
        state: reloaded
        enabled: yes
...