---
- name: Clean old apache config
  become: true
  become_user: root
  vars:
    - old_apache_config_file: /etc/apache2/conf-available/{{ git_name }}.conf
  when:
    - old_apache_config_file is file
  block:
    - name: Disable apache config
      shell: a2disconf {{ git_name }}.conf
    - nane: Remove old apache config file
      file:
        path: "{{ old_apache_config_file }}"
        state: absent

- name: Apache configuration
  become: true
  become_user: root
  block:
    - name: Install dependencies
      apt:
        name:
          - apache2
          - libapache2-mod-wsgi-py3
          - python3-jinja2
          - python3-markdown
          - python3-bs4
          - python3-jmespath
        state: latest

    - name: Deploy apache configuration
      template:
        src: httpd.conf
        dest: /etc/apache2/sites-available/{{ git_name }}.conf

    - name: Use a2* command to enable {{ git_name }} site
      shell: "{{ item }}"
      loop:
        - "a2enmod http2"
        - "a2enmod headers"
        - "a2ensite {{ git_name }}.conf"

    - name: Reload apache config
      systemd:
        name: apache2
        state: reloaded
        enabled: yes
...