---
- hosts: localhost
  gather_facts: true
  pre_tasks:
    - name: Ensure pre-requiste
      assert:
        that:
          - os_version in ansible_distribution in required.os
          - ansible_user_id == "root"
  roles:
    - role: setup
      git_clone: true
...