---
### DOC ### author: olivier perriot
### DOC ### state: dev
### DOC ### description: |
### DOC ###   something todo here http://192.168.1.18/show

- hosts: localhost
  roles:
    - setup

...
