---
- hosts: localhost
  gather_facts: true
  pre_tasks:
    - name: Ensure pre-requiste
      assert:
        that:
          - ansible_distribution == "Fedora"
          - ansible_distribution_major_version|int >= 28
          - ansible_user_id == "root"
  roles:
    - role: setup
      git_clone: true
...
