---
### DOC ### author: olivier perriot
### DOC ### state: dev
### DOC ### description: |
### DOC ###   something todo
### DOC ###   https://github.com/vengaar/liftree

- hosts: localhost
  roles:
    - setup

...
