---

- hosts: localhost
  tasks:

    - dnf:
        name:
          - httpd
          - python3-mod_wsgi
          - python3-jinja2
          - python3-json-logger
          - python3-markdown 
          - libselinux-python 
          # - setroubleshoot-server
        state: latest

    - file:
        path: /etc/liftree/conf.d/
        state: directory

    - copy:
        src: logging.conf
        dest: /etc/liftree/logging.conf

    - copy:
        src: liftree.conf
        dest: /etc/liftree/liftree.conf

    - copy:
        dest: /etc/liftree/conf.d/example.conf
        content: |
          ---
          name: /home/liftree/liftree/example
          ...

    - file:
        path: /home/liftree/liftree/wsgi/
        recurse: true
        state: directory
        mode: 0755

    - copy:
        src: httpd.conf
        dest: /etc/httpd/conf.d/liftree.conf

# About selinux

## setsebool -P httpd_enable_homedirs on
## setsebool -P httpd_read_user_content on
# semanage boolean --list | grep httpd | grep '(on'

# ls -Z /home/liftree/liftree
# semanage fcontext -a -t httpd_sys_content_t '/home/liftree/liftree(/.*)?'
# semanage fcontext -d "/home/liftree/liftree(/.*)?"
# restorecon -R -v /home/liftree/liftree/

# ls -Z /home/liftree/liftree.log
# semanage fcontext -a -t httpd_log_t /home/liftree/liftree.log
## semanage fcontext -a -t httpd_sys_rw_content_t /home/liftree/liftree.log
# semanage fcontext -d /home/liftree/liftree.log
## restorecon -v /home/liftree/liftree.log

    # - selinux:
    #     policy: targeted
    #     state: permissive

    - systemd:
        name: httpd
        state: restarted
